In [2]:
import numpy as np
from matplotlib import pyplot as plt

In [8]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

array([2, 3, 2, 2, 2, 1])

In [9]:
# > array([[ 0.,  1.,  0.],
# >        [ 0.,  0.,  1.],
# >        [ 0.,  1.,  0.],
# >        [ 0.,  1.,  0.],
# >        [ 0.,  1.,  0.],
# >        [ 1.,  0.,  0.]])

#### 如何在numpy中为数组生成单热编码？独热码

In [4]:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

In [10]:
one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [12]:
# 其实就是在我们的数字前面添加上一个标签而已啦
for i, k in enumerate(arr):
    print(i, k)

0 2
1 3
2 2
3 2
4 2
5 1


### END