In [1]:
import numpy as np

In [4]:
# 获取数组a和数组b之间的公共项。
a = np.array([1,2])
b = np.array([7,2])

In [5]:
np.intersect1d(a, b) # 类似于set的交集

array([2])

In [6]:
# 从数组a中删除数组b中的所有项
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [7]:
np.setdiff1d(a, b) # 注意a， b不要相反了哈

array([1, 2, 3, 4])

In [10]:
# 获取a和b元素匹配的位置。
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,1,2,7,4,9,4,9,8])
# 大家不知道还知不知道当初我们[arr % 2 == 1] 它其实用到的就是np中where函数,返回的是索引
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [13]:
# 获取5到10之间的所有项目 ,对where进行深入认识啦
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >=5) & (a <= 10))
a[index]

array([ 6,  9, 10])

### END