In [2]:
import numpy as np

In [4]:
# 生成一些数据
data = np.random.randn(2, 3)
data

array([[ 0.19607738,  1.4466713 ,  0.30083145],
       [ 1.19098428, -0.12340899,  0.38475064]])

In [5]:
# 乘法， 加法， 除法自己进行运算啦，是不是呢
data = data * 10
data

array([[ 1.96077375, 14.46671298,  3.00831451],
       [11.90984284, -1.23408987,  3.8475064 ]])

In [7]:
# shape函数
data.shape

(2, 3)

In [9]:
# 看我们的数组的类型啦
data.dtype

dtype('float64')

In [10]:
# 创建多维数组
data1 = [5, 6, 7]
arr1 = np.array(data1)
arr1

array([5, 6, 7])

In [11]:
data2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 查看它的维度
arr1.ndim

1

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 3)

In [15]:
# 创建零向量
zero_vec = np.zeros(10)
zero_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# 创建多维的零矩阵
zero_matrix = np.empty((2, 3))
zero_matrix

array([[ 1.96077375, 14.46671298,  3.00831451],
       [11.90984284,  1.23408987,  3.8475064 ]])

In [19]:
# 创建数组的时候指定数据的类型啦
arr3 = np.array([1, 2, 3], dtype = np.float32)
arr4 = np.array([4, 5, 6], dtype = np.int32)
arr4.dtype

dtype('int32')

In [22]:
# 进行数组的数据类型的转换啦, 但是会忽略掉一些数据，如果我们要转换成int则原来是float的会消失掉
arr4 = arr4.astype(np.float64)
arr4.dtype

dtype('float64')

### END