In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [6]:
arr1 = arr -arr

In [7]:
arr * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [8]:
arr > arr1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [12]:
# fnacy indexing
arr[1, 1]

5

In [18]:
%%html
<img src = "../img/axis.png", width = 400, height = 400>

### END