In [1]:
import numpy as np

In [2]:
arr = np.empty((8, 4))

In [3]:
arr

array([[1.35616574e+248, 3.05359770e-310, 9.86027971e-312,
        6.95285733e-310],
       [6.95285733e-310, 9.86027971e-312, 6.95285733e-310,
        9.86027971e-312],
       [6.95285733e-310, 6.95285733e-310, 9.86027971e-312,
        6.95285733e-310],
       [9.86027971e-312, 6.95285733e-310, 9.86027971e-312,
        6.95285733e-310],
       [6.95285733e-310, 9.86027971e-312, 6.95285733e-310,
        9.86027971e-312],
       [6.95285733e-310, 6.95285733e-310, 9.86027971e-312,
        6.95285733e-310],
       [9.86027971e-312, 6.95285733e-310, 9.86027971e-312,
        6.95285733e-310],
       [6.95285733e-310, 9.86027971e-312, 6.95285733e-310,
        9.86027971e-312]])

In [5]:
# 获取到的是其行向量是不是呢
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [6]:
# 获取 4，3， 0， 5行
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [7]:
# 是不是还记得负号的含义，就是逆序啦
arr[[-7, -5, -3]]

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.]])

In [8]:
# 花式索引与切片是不一样的，它总是把数据赋值到新的数组中来，是不是呢，我的天才们，爱你不需要进行商量的啦，哈哈

### END