In [1]:
import numpy as np

In [2]:
arr = np.arange(16).reshape(4, 4)

In [4]:
# 进行转置的操作
arr.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [5]:
# 进行点乘的操作啦
np.dot(arr, arr)

array([[ 56,  62,  68,  74],
       [152, 174, 196, 218],
       [248, 286, 324, 362],
       [344, 398, 452, 506]])

In [6]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
arr.transpose((1, 0)) # 不就是转置的效果而已吗，天才们呀,是不是呢

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

### END