In [1]:
import numpy as np

In [3]:
step = np.random.randint(0, 2, size = 1)
step

array([1])

In [118]:
step = np.random.randint(0, 2, size = 4)
step

array([1, 1, 1, 0])

In [121]:
steps = np.where(step > 0, 1, -1)
steps

array([ 1,  1,  1, -1])

In [128]:
# 进行累加的操作
sums = steps.cumsum()

In [124]:
sums

array([1, 2, 3, 2], dtype=int32)

### END